### ISSUE TITLE
control-c causes hang

### ISSUE THREAD

**Issue by docwhat** [benjdewan/pachelbel#4]
If you try to interrupt (control-c, aka the INT signal or signal 2) pachelbel, it then hangs...

I expect it to clean up and exit or if it is unable to stop, to at least not hang.

**Comment by benjdewan** [comment]
This appeared to be an issue with the progress bar library I was used. [v2.2.0](https://github.com/benjdewan/pachelbel/releases/tag/v2.2.0) debuts a somewhat clunky, but much simpler progress indicator that appears to fix the problem.

If you can still reproduce the hang, please post the configuration yaml you're using and re-open this.
