### ISSUE TITLE
Error updating notes on an existing deployment with the same scaling info

### ISSUE THREAD

**Issue by amsantavicca** [benjdewan/pachelbel#9]
If the `scalings` value is the same in the config and on the existing deployment when updating the `notes` on the deployment, Pachelbel will fail with the following error:

```
[Unable to resize 'my-cool-deployment-name':
[map[units:[is already at that value]]]]
```

Not sure if this is a _new_ problem (i.e. the Compose API response has changed) or if this issue just hasn't been hit before.

Looking at the code, it seems that when we run `Update` in `runner/runner.go` we try _all_ of the update-able items whether they need updated or not.

**Comment by benjdewan** [comment]
There is logic in the config package that should zero out the scaling value which, in turn, disables that update, but it looks like that logic was not working properly in the case where a scaling was set. Hopefully it is now.
